services:
  - type: web
    name: ragdocengine-backend
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DEBUG
        value: "False"
      - key: CHROMA_DB_PATH
        value: ./chroma_db
